"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import Image from "next/image";

const ease = [0.16, 1, 0.3, 1] as const;

type Tab = "terms" | "privacy" | "safety";

const TABS: { id: Tab; label: string }[] = [
  { id: "terms", label: "Terms of Use" },
  { id: "privacy", label: "Privacy Policy" },
  { id: "safety", label: "Clinical Safety" },
];

const CONTENT: Record<Tab, { heading: string; body: React.ReactNode }> = {
  terms: {
    heading: "Terms of Use",
    body: (
      <>
        <p>By accessing or using Mendalia AI ("the Platform"), operated by Sirohi Corporation Pty Ltd (ABN 73 683 661 181), you agree to be bound by these Terms of Use.</p>
        <h4>1. Intended Use</h4>
        <p>Mendalia AI is designed as a clinical documentation and decision-support tool for use by qualified, registered medical professionals. It is not a substitute for clinical judgement, diagnosis, or treatment by a licensed healthcare provider.</p>
        <h4>2. Account Responsibility</h4>
        <p>You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorised access.</p>
        <h4>3. Prohibited Use</h4>
        <p>You must not use the Platform to store, transmit, or process data in violation of applicable privacy legislation, including the Australian Privacy Act 1988, GDPR, HIPAA, or India's DPDP Act 2023.</p>
        <h4>4. Intellectual Property</h4>
        <p>All software, AI models, interfaces, and content on the Platform are the exclusive intellectual property of Sirohi Corporation Pty Ltd. No licence is granted beyond what is necessary to use the Platform as intended.</p>
        <h4>5. Limitation of Liability</h4>
        <p>To the maximum extent permitted by law, Sirohi Corporation Pty Ltd is not liable for any clinical decisions made in reliance on the Platform's output. AI-generated content must always be reviewed and validated by the treating clinician.</p>
        <h4>6. Governing Law</h4>
        <p>These Terms are governed by the laws of New South Wales, Australia. Disputes will be subject to the exclusive jurisdiction of NSW courts.</p>
      </>
    ),
  },
  privacy: {
    heading: "Privacy Policy",
    body: (
      <>
        <p>Sirohi Corporation Pty Ltd ("we", "us") is committed to protecting the privacy of clinicians and patients whose data is processed through Mendalia AI. This Policy explains how we collect, use, and safeguard personal information.</p>
        <h4>1. Information We Collect</h4>
        <p>We collect account information (name, email, organisation), session metadata, and clinical documentation generated during use of the Platform. We do not sell or share this data with third parties for marketing purposes.</p>
        <h4>2. How We Use Your Data</h4>
        <p>Data is used solely to provide and improve the Platform's clinical documentation features. De-identified, aggregated data may be used to improve AI model performance with your consent.</p>
        <h4>3. Data Storage & Security</h4>
        <p>All data is encrypted at rest (AES-256) and in transit (TLS 1.3). Clinical data is stored on Google Cloud Platform infrastructure in the Asia-Pacific region. We maintain controls aligned with SOC 2, ISO 27001, and CE standards.</p>
        <h4>4. Compliance</h4>
        <p>We operate in accordance with the Australian Privacy Act 1988 (APP), GDPR (EU), HIPAA (US), and India's DPDP Act 2023.</p>
        <h4>5. Your Rights</h4>
        <p>You have the right to access, correct, or request deletion of your personal data at any time. Contact us at <a href="mailto:privacy@mendalia.com">privacy@mendalia.com</a>.</p>
        <h4>6. Cookies</h4>
        <p>We use essential cookies for authentication and session management only. We do not use tracking or advertising cookies.</p>
      </>
    ),
  },
  safety: {
    heading: "Clinical Safety",
    body: (
      <>
        <p>Mendalia AI is built with clinical safety as a first principle. This statement outlines our approach to responsible AI deployment in clinical environments.</p>
        <h4>1. Decision Support, Not Decision Making</h4>
        <p>Mendalia AI is a clinical decision-support tool. All AI-generated outputs — including SOAP notes, differential diagnoses, clinical letters, and case summaries — are intended to assist, not replace, the clinical judgement of a licensed healthcare professional.</p>
        <h4>2. Clinician-in-the-Loop</h4>
        <p>Every output generated by the Platform must be reviewed, validated, and approved by the treating clinician before being used in patient care or placed in a medical record. The clinician retains full clinical and legal responsibility for all decisions.</p>
        <h4>3. AI Transparency</h4>
        <p>We clearly mark all AI-generated content within the Platform interface. Confidence indicators and reasoning traces are available where applicable. We do not obscure model uncertainty.</p>
        <h4>4. Bias & Limitations</h4>
        <p>AI models may reflect biases present in training data. Clinicians should apply professional judgement, particularly for underrepresented populations, rare conditions, and paediatric cases.</p>
        <h4>5. Incident Reporting</h4>
        <p>If you identify a clinical safety concern related to Platform output, please report it immediately to <a href="mailto:safety@mendalia.com">safety@mendalia.com</a>. We investigate all safety reports and maintain a register in accordance with applicable medical device and software regulations.</p>
        <h4>6. Regulatory Alignment</h4>
        <p>Mendalia AI is designed in alignment with the TGA's Software as a Medical Device (SaMD) framework (Australia), FDA guidance on AI/ML-based SaMD (US), and CE marking requirements (EU MDR).</p>
      </>
    ),
  },
};

function LegalModal({ initialTab, onClose }: { initialTab: Tab; onClose: () => void }) {
  const [active, setActive] = useState<Tab>(initialTab);
  const { heading, body } = CONTENT[active];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.22 }}
      onClick={onClose}
      style={{
        position: "fixed", inset: 0, zIndex: 200,
        background: "rgba(0,0,0,0.76)",
        backdropFilter: "blur(10px)",
        display: "flex", alignItems: "center", justifyContent: "center",
        padding: "24px 16px",
      }}
    >
      <motion.div
        initial={{ opacity: 0, y: 28, scale: 0.97 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: 16, scale: 0.97 }}
        transition={{ duration: 0.4, ease }}
        onClick={(e) => e.stopPropagation()}
        style={{
          background: "#0f0f0f",
          border: "1px solid rgba(255,255,255,0.08)",
          borderRadius: 22,
          width: "100%",
          maxWidth: 600,
          maxHeight: "85vh",
          display: "flex",
          flexDirection: "column",
          boxShadow: "0 40px 100px rgba(0,0,0,0.7), 0 0 0 1px rgba(255,255,255,0.03) inset",
          overflow: "hidden",
        }}
      >
        {/* Header */}
        <div style={{
          padding: "28px 32px 0",
          borderBottom: "1px solid rgba(255,255,255,0.06)",
          flexShrink: 0,
        }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 22 }}>
            <span style={{
              fontFamily: "var(--font-montserrat), sans-serif",
              fontSize: 11, fontWeight: 700,
              letterSpacing: "0.12em", textTransform: "uppercase",
              color: "rgba(255,255,255,0.28)",
            }}>
              Mendalia AI · Legal
            </span>
            <button
              onClick={onClose}
              style={{
                width: 28, height: 28, borderRadius: "50%",
                background: "rgba(255,255,255,0.06)", border: "none",
                cursor: "pointer", display: "flex", alignItems: "center",
                justifyContent: "center", color: "rgba(255,255,255,0.4)",
                fontSize: 15, transition: "background 0.15s",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.background = "rgba(255,255,255,0.12)")}
              onMouseLeave={(e) => (e.currentTarget.style.background = "rgba(255,255,255,0.06)")}
            >
              ×
            </button>
          </div>

          {/* Tabs */}
          <div style={{ display: "flex", gap: 4 }}>
            {TABS.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActive(tab.id)}
                style={{
                  fontFamily: "var(--font-montserrat), sans-serif",
                  fontSize: 13, fontWeight: 600,
                  letterSpacing: "-0.01em",
                  padding: "8px 16px",
                  borderRadius: "8px 8px 0 0",
                  border: "none", cursor: "pointer",
                  transition: "background 0.15s, color 0.15s",
                  background: active === tab.id ? "rgba(255,255,255,0.07)" : "transparent",
                  color: active === tab.id ? "rgba(255,255,255,0.9)" : "rgba(255,255,255,0.32)",
                  borderBottom: active === tab.id ? "2px solid rgba(255,255,255,0.55)" : "2px solid transparent",
                }}
                onMouseEnter={(e) => { if (active !== tab.id) e.currentTarget.style.color = "rgba(255,255,255,0.55)"; }}
                onMouseLeave={(e) => { if (active !== tab.id) e.currentTarget.style.color = "rgba(255,255,255,0.32)"; }}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>

        {/* Content */}
        <AnimatePresence mode="wait">
          <motion.div
            key={active}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            transition={{ duration: 0.22, ease: [0.4, 0, 0.2, 1] }}
            style={{
              overflowY: "auto",
              padding: "32px 32px 36px",
              flex: 1,
            }}
          >
            <style>{`
              .legal-content h4 {
                font-family: var(--font-montserrat), sans-serif;
                font-size: 12px;
                font-weight: 700;
                letter-spacing: 0.08em;
                text-transform: uppercase;
                color: rgba(255,255,255,0.55);
                margin: 24px 0 8px;
              }
              .legal-content p {
                font-family: var(--font-montserrat), sans-serif;
                font-size: 13.5px;
                line-height: 1.78;
                color: rgba(255,255,255,0.48);
                letter-spacing: -0.005em;
              }
              .legal-content a {
                color: rgba(255,255,255,0.65);
                text-decoration: underline;
                text-underline-offset: 3px;
              }
            `}</style>
            <h2 style={{
              fontFamily: "var(--font-montserrat), sans-serif",
              fontSize: 22, fontWeight: 800,
              color: "#ffffff", letterSpacing: "-0.03em",
              marginBottom: 18,
            }}>
              {heading}
            </h2>
            <div className="legal-content">
              {body}
            </div>
          </motion.div>
        </AnimatePresence>
      </motion.div>
    </motion.div>
  );
}

export default function Footer() {
  const [legalTab, setLegalTab] = useState<Tab | null>(null);

  const footerLink = (label: string, tab: Tab) => (
    <button
      key={tab}
      onClick={() => setLegalTab(tab)}
      style={{
        fontFamily: "var(--font-montserrat), sans-serif",
        fontSize: 12.5, fontWeight: 500,
        color: "rgba(255,255,255,0.38)",
        letterSpacing: "-0.005em",
        background: "none", border: "none",
        cursor: "pointer", padding: 0,
        transition: "color 0.15s",
      }}
      onMouseEnter={(e) => (e.currentTarget.style.color = "rgba(255,255,255,0.75)")}
      onMouseLeave={(e) => (e.currentTarget.style.color = "rgba(255,255,255,0.38)")}
    >
      {label}
    </button>
  );

  return (
    <>
      <AnimatePresence>
        {legalTab && <LegalModal initialTab={legalTab} onClose={() => setLegalTab(null)} />}
      </AnimatePresence>

      <footer style={{ background: "#0A0A0A", padding: "64px 0 40px", position: "relative" }}>
        <div aria-hidden style={{ position: "absolute", top: 0, left: 0, right: 0, height: 1, background: "rgba(255,255,255,0.06)", pointerEvents: "none" }} />

        <div style={{ maxWidth: 1120, margin: "0 auto", padding: "0 32px" }}>

          {/* Logo + tagline */}
          <div style={{ display: "flex", flexDirection: "column", gap: 20, marginBottom: 52 }}>
            <div style={{ height: 44, width: 140, position: "relative", flexShrink: 0 }}>
              <Image
                src="/mendalia-logo.png" alt="Mendalia"
                width={1563} height={1563}
                style={{
                  position: "absolute", height: 120, width: 120, objectFit: "contain",
                  top: "50%", left: "50%", transform: "translate(-60%, -46%)",
                  filter: "brightness(0) invert(1)", opacity: 0.9,
                }}
              />
            </div>
            <p style={{
              fontFamily: "var(--font-montserrat), sans-serif",
              fontSize: "clamp(15px, 1.8vw, 20px)", fontWeight: 600,
              color: "rgba(255,255,255,0.72)", letterSpacing: "-0.025em",
              lineHeight: 1.5, maxWidth: 540,
            }}>
              The AI-native Ambient OS, with Case Augmentation.{" "}
              <span style={{ color: "rgba(255,255,255,0.38)", fontWeight: 400 }}>
                From spoken words to complete diagnosis. End to end.
              </span>
            </p>
          </div>

          {/* Divider */}
          <div aria-hidden style={{ height: 1, background: "rgba(255,255,255,0.07)", marginBottom: 32 }} />

          {/* Bottom row */}
          <div style={{ display: "flex", flexWrap: "wrap", alignItems: "flex-start", justifyContent: "space-between", gap: 32 }}>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              <p style={{
                fontFamily: "var(--font-montserrat), sans-serif",
                fontSize: 13, fontWeight: 700,
                color: "rgba(255,255,255,0.82)", letterSpacing: "-0.01em",
              }}>
                Mendalia AI
              </p>
              <p style={{
                fontFamily: "var(--font-montserrat), sans-serif",
                fontSize: 11.5, color: "rgba(255,255,255,0.36)",
                letterSpacing: "-0.005em", lineHeight: 1.7,
              }}>
                Trading under Sirohi Corporation Pty Ltd<br />
                ABN: 73&nbsp;683&nbsp;661&nbsp;181 &middot; ACN: 683&nbsp;661&nbsp;181<br />
                Headquartered in Sydney, Australia
              </p>
            </div>

            <nav style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px 24px" }}>
              {footerLink("Terms", "terms")}
              {footerLink("Privacy Policy", "privacy")}
              {footerLink("Clinical Safety", "safety")}
            </nav>
          </div>

          <p style={{
            fontFamily: "var(--font-montserrat), sans-serif",
            fontSize: 11, color: "rgba(255,255,255,0.22)",
            letterSpacing: "-0.005em", marginTop: 28,
          }}>
            &copy; {new Date().getFullYear()} Sirohi Corporation Pty Ltd. All rights reserved.
          </p>
        </div>
      </footer>
    </>
  );
}
